#Module to send email to the list of Contacts 
from construct.models import Contact_list, User
from construct import mail, Message, app
import requests
 
def SendNotificationAsContractor(Type):
    Users=User.query.all()
    contact_list = []
    
    for user in Users:
        if user.role == "Client" or user.role == "Consultant":
            contact_list.append(user.email_address)
    
    msg = Message('Project Delay Alert', sender = 'sdousmanflask@gmail.com', recipients = contact_list)
    msg.body = "A new " +  Type + " was created by the contractor"
    mail.send(msg)

def SendNotificationAsClient(Type):
    Users=User.query.all()
    contact_list = []
    
    for user in Users:
        if user.role == "Contractor" or user.role == "Consultant":
            contact_list.append(user.email_address)
    
    
    msg = Message('Project Delay Alert', sender = 'sdousmanflask@gmail.com', recipients = [user.email_address])
    msg.body = "A new " +  Type + " was created by the Consultant/Client"
    mail.send(msg)

def SendDelayReport():
    Users=User.query.all()
    contact_list = []
    
    for user in Users:
        contact_list.append(user.email_address)
   # print(contact_list) test print <---- prints the array of emails. works!
   # Opens and sends the pdf generated by the PDFEmail function that calls this function
    with app.open_resource("newpdf.pdf") as fp:
        msg = Message('Project Delay Report', sender = 'sdousmanflask@gmail.com', recipients = contact_list)
        msg.body = "A new Delay Report was Created and Sent by the contractor"
        msg.attach("newpdf.pdf", "application/pdf", fp.read()) 
        mail.send(msg)

def send_sms(Message):
    Users=User.query.all()

    for user in Users:
            user_id="15896"     #credentials are currently hard-coded,should pass them as environmental variables
            api_key= "c977qWgaQfGYfZHoXJc1"
            sender_id="NotifyDEMO"
            message= Message  #Message is passed as a parameter to this function by the caller function
         
            request_string="https://app.notify.lk/api/v1/send?"+"user_id="+user_id+"&api_key="+api_key+"&sender_id="+sender_id+"&to="+user.contact_number+"&message="+message
            print(request_string) #Test- to inspect the generated URL
            r = requests.get(request_string) #Gets JSON response from the sms API
            
            print(r.text) #Test- to inspect the response from the SMS API

     